### ISSUE TITLE
How to define indexs in rest-hapi schema?

### ISSUE THREAD

**Issue by arunkatariaoodles** [JKHeadley/rest-hapi#100]
Hi,
I want to define indexes in a rest-hapi schema. In ExpressJs we have to define indexes in the schema like that:- 
var userSchema = new Schema({
name: String,
location: {
       type: {type: String},
       coordinates: []
   } // field level
});
userSchema.index({ location: '2dsphere' }); // schema level

**Comment by JKHeadley** [comment]
Hi @arunkatariaoodles 

Indexes are handled with mongoose. Here's an example via their [docs](http://mongoosejs.com/docs/guide.html):

```
var animalSchema = new Schema({
    name: String,
    type: String,
    tags: { type: [String], index: true } // field level
  });

  animalSchema.index({ name: 1, type: -1 }); // schema level
```

**Comment by arunkatariaoodles** [comment]
Hi @JKHeadley 
Yes indexes are handled in mongoose, But when I am defining the schema in rest-hapi like that:

`module.exports = function(mongoose) {
    var modelName = "user";
    var Types = mongoose.Schema.Types;
    var Schema = new mongoose.Schema({
        name: {
            type: Types.String,
        },
        location: [{
            type: {
                type: Types.String,
                default: "Point"
            },
            coordinates: {
                type: [Types.Number]
            }
        }]
    }, {
        collection: modelName
    });
    Schema.index({ location: '2dsphere' });

    Schema.statics = {
        collectionName: modelName,
        routeOptions: {
            allowCreate: false,
            updateAuth: false,
            alias: "user"
        }
    };

    return Schema;
};`

It will show error in the creation of user data.

**Comment by JKHeadley** [comment]
You could try:

```javascript
module.exports = function(mongoose) {
var modelName = "user";
var Types = mongoose.Schema.Types;
var Schema = new mongoose.Schema({
name: {
type: Types.String,
},
        location: {
            type: [Number],  // [<longitude>, <latitude>]
            index: '2dsphere',     // create the geospatial index
        },
coordinates: {
type: [Types.Number]
}
}]
}, {
collection: modelName
});

Schema.statics = {
    collectionName: modelName,
    routeOptions: {
        allowCreate: false,
        updateAuth: false,
        alias: "user"
    }
};

return Schema;

};
```

**Comment by arunkatariaoodles** [comment]
I had tried this it will show this error " planner returned error: unable to find index for $geoNear query"  while fetching the user data. And after executing "db.user.ensureIndex( { "location.0" : "2dsphere" } )" this query on shell it will work. I don't want to run this query, it should automatically ensure the index once the data is created.

**Comment by JKHeadley** [comment]
Hmm, I'm not sure where the error is coming from, but unfortunately I think it's more related to mongoose or mongo than rest-hapi. Maybe try checking their issues? I can tell you that I've successfully used the code above on several of my own projects. Best of luck.

**Comment by arunkatariaoodles** [comment]
Ok, thanks for your support.
