### ISSUE TITLE
Support for hapi 17

### ISSUE THREAD

**Issue by shiva** [JKHeadley/rest-hapi#114]
Hapi 17 included a set of breaking changes. Is there support planned for making rest-hapi compatible with latest hapi version?

**Comment by JKHeadley** [comment]
Yes, Hapi 17 support will be part of the [v1 release](https://github.com/JKHeadley/rest-hapi/milestone/9).

**Comment by shiva** [comment]
Is there anything I can do to help?

**Comment by JKHeadley** [comment]
I appreciate the offer! I expect to finish the updates within the next few days. I'm always open to contributions however I would advise to wait for the next release due to all the changes.

**Comment by shiva** [comment]
understand. Thanks.

**Comment by JKHeadley** [comment]
@shiva Hapi 17 is now supported with rest-hapi v1.0.0

**Comment by shiva** [comment]
Awesome! That was fast and thanks
