### ISSUE TITLE
1.0.0 Release Notes

### ISSUE THREAD

**Issue by JKHeadley** [JKHeadley/rest-hapi#120]
**rest-hapi** v1.0.0 is finally here and comes with a few major updates, the most important of which is the addition of [Hapi 17](https://github.com/hapijs/hapi/issues/3658) support. The code has been cleaned up, re-organized, and optimized. All code commits now have to pass eslint checks and are automatically styled using [prettier](https://prettier.io/), and code coverage reports are integrated with CI and being published using [codecov](https://codecov.io/gh/JKHeadley/rest-hapi). There is still plenty of room for improvement, but overall I believe the project is in a solid state. I'd like to give a big thanks to everyone who has reported bugs, suggested improvements, and submitted PRs. It is my hope that this project continues to grow and provide utility to those looking for rapid endpoint development.

Below is a list of changes/updates from v0.43.0 -> v1.0.0:

### Hapi 17 Updates
These mainly affect endpoint handler formats, but I highly suggest viewing the [Hapi 17 release notes](https://github.com/hapijs/hapi/issues/3658) to understand all the effects. The other big area affected is mrhorse policies, which you can read about [here](https://github.com/mark-bradshaw/mrhorse#updating).

### Replaced `gulp` with `npm`
All scripts, including tests and seeding, are now managed by npm rather than gulp.

### Removed the `errorHelper` utility
With the many optimizations introduced with Hapi 17 and an adoption of async/await, the error handling system has been greatly simplified, removing the need for this utility.

## Other Improvements

- Major adoption of async/await
- Replaced `Q` promise library with es6 promises
- Code style enforcement through eslint and prettier
- Removed several unused dependencies and utilities
- Added CI for code coverage reports

**Comment by bmgdev** [comment]
have you found a workaround for a global cors setting?   https://github.com/hapijs/hapi/issues/3658#issuecomment-398804025

**Comment by JKHeadley** [comment]
@bmgdev I haven't yet unfortunately.
