### ISSUE TITLE
Access to model from a custom endpoint handler

### ISSUE THREAD

**Issue by shiva** [JKHeadley/rest-hapi#125]
the model is an internal property of rest-hapi. How do I get access to a populated model ? generateModels is mutable and seems to re-load the models. 

I'd think this is required in order to invoke any of the CRUD methods on restHapi.

**Comment by JKHeadley** [comment]
I usually access the models using the `mongoose.model` function, something like:
```javascript
const User = mongoose.model('user')
```

Is that what you are referring to?

**Comment by shiva** [comment]
Thanks. How very dumb of me. :)
