### ISSUE TITLE
Engine restrictions

### ISSUE THREAD

**Issue by moacirosa** [JKHeadley/rest-hapi#13]
I'm using `yarn` as package manager and sometimes I get some warnings about the engine being not compatible. It's currently fixed as `6.0.0`. I've just run the tests over `v6.8.0` and all tests are green. Do you really have this restriction for some reason?

```json
{
  "name": "rest-hapi",
  "version": "0.15.1",
  "description": "A RESTful API generator for hapi",
  "main": "rest-hapi.js",
  "bin": {
    "rest-hapi-cli": "./rest-hapi-cli.js"
  },
  "engines": {
    "node": "6.0.0",
    "npm": "4.0.5"
  },
  ...
```

**Comment by JKHeadley** [comment]
@moacirosa, just meant to add those as suggestions. Changed the versions to be approximate, hopefully that will remove your warnings.

**Comment by moacirosa** [comment]
Wow! That was fast! Thanks! :+1: :smile:

**Comment by JKHeadley** [comment]
👍
