### ISSUE TITLE
Array of strings not working

### ISSUE THREAD

**Issue by mikaoelitiana** [JKHeadley/rest-hapi#149]
**Describe the bug**
I am creating a model with an array of string as one of it's properties but I can't insert data there.

**To Reproduce**

1. Create a model with one properties as an Array of String
```
//...
new mongoose.Schema({
    name: Types.String,
    tags: [Types.String]
  });
```

2. Try to insert some data like 

```
//...
"tags": ["one", "two"]
```

3. A `400` status code is received : 

```
{
	"statusCode": 400,
	"error": "Bad Request",
	"message": "Invalid request payload input"
}
```
**Expected behavior**
Tags data should be inserted

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Firefox
 - Version 1.3.3

**Comment by JKHeadley** [comment]
@mikaoelitiana thanks for pointing this out. I'll try to look into it soon.

**Comment by Clemssss** [comment]
@JKHeadley Hey, what about array of strings now ? Thanks for your answer.

**Comment by JKHeadley** [comment]
@Clemssss thanks for bringing my attention to this. @mikaoelitiana apologies for the delay.

I believe the issue here is the syntax you are using. Instead of 
```
tags: [Types.String]
```
try:
```
tags: { type: [String] }
```

**Comment by Clemssss** [comment]
@JKHeadley Thanks to you, for your time and your availability ! And exactly it works !
(rest-hapi is really really good, the saving time is insane, nice idea !!!!)

**Comment by JKHeadley** [comment]
@Clemssss glad you find it useful!
