### ISSUE TITLE
Configuration with auditLogTTL unspecified 

### ISSUE THREAD

**Issue by jozefb** [JKHeadley/rest-hapi#161]
**Describe the bug**
When configuration property _auditLogTTL_ is unspecified then TTL index of **auditLog** collection is created with _expireAfterSeconds_ field value set to "null". This causes the following error logged by MongoDB:
> E INDEX    [TTLMonitor] ttl indexes require the expireAfterSeconds field to be numeric but received a type of null, skipping ttl job for: { v: 2, key: { date: 1 }, name: "date_1", ns: "resource-index.auditLog", expireAfterSeconds: null, background: true }

As stated in https://jira.mongodb.org/browse/SERVER-37983, creation such indexes in future MongoDB versions will be rejected

**To Reproduce**

1. Leave _auditLogTTL_ configuration property unspecified
`auditLogTTL: ` and set `enableAuditLog` property to **true**

2. **auditLog** collection is created with _expireAfterSeconds_ field value set to "null"

**Expected behavior**
TTL index is not created

**Desktop:**
 - OS: macOS 
 - Version 10.14.1 

**Additional context**
Proposed fix in https://github.com/JKHeadley/rest-hapi/blob/master/models/audit-log.model.js where mongoose _expires_ field is created conditionally:

```
...
  let Types = mongoose.Schema.Types
  let dateField = {`
    type: Types.Date,
    default: () => {
      return Date.now()
    }
  }

  if (Config.auditLogTTL) {
    dateField.expires = Config.auditLogTTL
  }

  let Schema = new mongoose.Schema(
    {
      date: dateField,
      method: {
...
```

**Comment by JKHeadley** [comment]
@jozefb Great catch! I'll try to integrate your fix ASAP. Feel free to open a Pull Request if you like.

**Comment by hilanmiao** [comment]
> @jozefb Great catch! I'll try to integrate your fix ASAP. Feel free to open a Pull Request if you like.

I have encountered the same problem.i used @jozefb's solution.If the official has a better solution, fix it.Thank you very much.

**Comment by JKHeadley** [comment]
fixed with https://github.com/JKHeadley/rest-hapi/pull/205
