### ISSUE TITLE
Cannot define model property 'id'

### ISSUE THREAD

**Issue by davad** [JKHeadley/rest-hapi#163]
## Describe the bug
Schema can't contain a user-defined 'id' property. Is this by design?

## To Reproduce

I have a model with a "friendly ID".

Example schema:
```
const Schema = new mongoose.Schema({
    name: mongoose.Types.String,
    description: mongoose.Types.String,
    id: mongoose.Types.String,
})
```

When I try to create a document, the `id` is silently dropped. When I try to update a document, the `id` throws a Joi validation error like this:

```
ValidationError: "value" at position 0 fails because ["id" is not allowed], "testCreateModel" must be an object
```

It looks like [this line](https://github.com/JKHeadley/rest-hapi/blob/9d03bdf4fe8b6be9481e9cadeda94b2882b03c3a/utilities/joi-mongoose-helper.js#L683) is responsible for the Joi error. I'm not sure about the `id` being silently dropped.

## Expected behavior
I expect to be able to define any property name. Also, if a schema doesn't allow a particular property name, I expect a validation error when attempting to create the document.

## Screenshots
Screenshot of the validation error using the schema above and trying to POST this object:
```
[{"name":"Test", "id":"Test"}
```
<img width="1385" alt="screen shot 2019-02-27 at 3 05 43 pm" src="https://user-images.githubusercontent.com/190387/53519413-37b0f380-3aa1-11e9-91a4-3c9c9d1021b0.png">

## Desktop (please complete the following information):
 - OS: macOS
 - Browser: N/A (curl)

**Comment by JKHeadley** [comment]
@davad `id` is used as a virtual property to get a string representation of a document's `_id`. I'm not sure if there are any side effects to overriding the virtual property with a user defined one.
