### ISSUE TITLE
Access request object in middleware

### ISSUE THREAD

**Issue by JKHeadley** [JKHeadley/rest-hapi#20]
Reference #19

**Comment by jobberwalker** [comment]
Hello, that would be perfect to have request object in middleware functions. For now, I had to register hapi js server extensions.
Thanks
JB

**Comment by JKHeadley** [comment]
@jobberwalker, in case you haven't already, you can view #19 for a current workaround.

**Comment by tamias** [comment]
I'm curious about the progress of this feature.  I've implemented a custom create endpoint, as suggested in #19.  However, I need to access the request object for all the CRUD endpoints, to make sure users can only access their own content.  List in particular seems to have a lot of code that goes into generating the endpoint, which I think I'd have to duplicate.
Thanks!

**Comment by JKHeadley** [comment]
@tamias I haven't had a lot of time for features lately, but given the amount of interest in this feature I will try to work this in the next version.  

For now you should still be able to take advantage of most of the generated code with the below workaround for list.  The main functionality that you will lose is the Joi validation, swagger docs, and generate scopes/authorization.

```
'use strict';

const RestHapi = require('rest-hapi');

module.exports = function (server, mongoose, logger) {
      server.route({
            method: 'GET',
            path: '/pathName',
            config: {
                handler: function(request, reply) {
                    /* modify request.payload here and access auth info through request.auth.credentials */

                    const Model = mongoose.model('modelName');
                    return RestHapi.list(Model, request.query, logger)
                        .then(function (result) {
                            return reply(result);
                        })
                        .catch(function (error) {
                            return reply(error);
                        });
                },
                tags: ['api'],
                plugins: {
                    'hapi-swagger': {}
                }
            }
        });
};
```
