### ISSUE TITLE
$where does not support real raw queries

### ISSUE THREAD

**Issue by jobberwalker** [JKHeadley/rest-hapi#21]
Hello,
For $where field when provided simple selection like e.g.  {"doc_nr": "1005"} works perfectly fine. For more complex including special operators (with $) it does not work, e.g.: { "doc_nr": {$ne: "1005"}}

result:

ERROR    node_modules/rest-hapi/utilities/error-helper.js:27:11 api/docs/List — error:  SyntaxError: Unexpected token $ in JSON at position 17

Thanks
JB

**Comment by JKHeadley** [comment]
@jobberwalker, if you are testing this in the swagger docs, you have to put quotes around all the query commands. Try: { "doc_nr": { "$ne": "1005"}}

**Comment by jobberwalker** [comment]
Hello JKHeadley,
Yes you are right. This is working perfectly fine with quotes.
JB
