### ISSUE TITLE
$sort with array

### ISSUE THREAD

**Issue by bielcapanema** [JKHeadley/rest-hapi#22]
How can I sort the results with a array length ?

My collection have an 'likes' field that is an array of user ids, and I want to return the documents sorted with 'likes' length.

Can someone help me? #

**Comment by JKHeadley** [comment]
Hi @bielcapanema, there currently isn't any built in support for sorting by array length, however you could try the following approach:

Add a property, "likesCount", to your collection (here we're calling the collection "comment"). In your model definition, add an update middleware function that updates "likesCount" to be the length of the "likes" array, whenever "likes" is updated.  You can then sort by the "likesCount" property.

You can learn about middleware functions [here](https://github.com/JKHeadley/rest-hapi#middleware)

See the code below for an example:

```javascript
'use strict';

const Q = require('q');
const RestHapi = require('rest-hapi');

module.exports = function (mongoose) {
    var modelName = "comment";
    var Types = mongoose.Schema.Types;
    var Schema = new mongoose.Schema({
        text: {
            type: Types.String,
        },
        likes: {
            type: [Types.ObjectId]
        },
        likesCount: {
            type: Types.Number,
            allowOnUpdate: false,
            default: 0
        }
    }, { collection: modelName });

    Schema.statics = {
        collectionName: modelName,
        routeOptions: {
            update: {
                post: function (payload, result, Log) {
                    const Comment = mongoose.model('comment');

                    if (payload.likes) {
                        return RestHapi.update(Comment, result._id, { likesCount: payload.likes.length }, Log)
                    }
                    else {
                        return Q.when(result);
                    }
                }
            }
        }
    };
    
    return Schema;
};
```
