### ISSUE TITLE
How to use SSL with rest-hapi?

### ISSUE THREAD

**Issue by tuutoo** [JKHeadley/rest-hapi#246]
Is it possible start the server with https protocol?
I have my SSL certificates but don't know how to configure to use https.

**Comment by tuutoo** [comment]
I have found a solution and it works now. :D 

in **api.js**

1. at the beginning, add 1 line to require fs module.
2. add a tls node in below section.

**const fs = require('fs')**
...
...
let server = Hapi.Server({
      port: 3001,
      **tls: {
        key: fs.readFileSync('/your_ssl_key_path/privkey.pem'),
        cert: fs.readFileSync('/your_ssl_key_path/fullchain.pem')
      },**
      routes: {
        validate: {
          failAction: async (request, h, err) => {
            RestHapi.logger.error(err);
            throw err;
          }
        }
      }
    })

**Comment by JKHeadley** [comment]
@tuutoo glad you worked it out. Thanks for sharing! ;)
