### ISSUE TITLE
use $or on restHapi List

### ISSUE THREAD

**Issue by cristianpedroso** [JKHeadley/rest-hapi#26]
When i try to make a list using restHapy i recive this error:

MongoError: $or must be an array
```
restHapi.list(model, {"$or" : [{name:"ases"},{framework:"asease"}]},Log).then(function (result) {
```

**Comment by JKHeadley** [comment]
@cristianpedroso it looks like you are trying to perform a raw mongoose query.  If you would like to do that through rest-hapi, you can try using the `$where` query parameter like so:

```javascript
restHapi.list(model, { $where: {"$or" : [{name:"ases"},{framework:"asease"}]} }, Log).then(function (result) {
```

**Comment by cristianpedroso** [comment]
thats makes more sense now. Thanks!
