### ISSUE TITLE
How to do some enhancement or changes in existing API created automatically by Rest-Hapi.

### ISSUE THREAD

**Issue by parveen-oodles** [JKHeadley/rest-hapi#28]
Hi,
First of all thanks for providing awesome module like rest-hapi. I required so many time that if there is somehow i can change or modify the auto created API according to my requirement. Like if i add one flag, if that flag value is true than i call one of my method and than append the result of my method with the result we are going to send to the client. Is this functionality currently exists or not and if exists than would appreciate if you please let me know.

Thanks

**Comment by JKHeadley** [comment]
I'm not sure if I understand your question exactly, but it sounds like you want to modify the response before it is sent to the client.  This is something that you should be able to accomplish with the [middleware](https://github.com/JKHeadley/rest-hapi#middleware) functions.

**Comment by parveen-oodles** [comment]
Thanks for your valuable reply JKHeadley , Yes you are right we can do the work via middle-ware but not in case of update API of association . So if you update the code according to my issue i.e. **[https://github.com/JKHeadley/rest-hapi/issues/27]** than this will automatically resolved.

And apart from that i just want a place where i can write my custom function that's not related to DB lets say any work i need to do some calculation but as now API created auto so i haven't any code where i can write my logic's so if possible than please add some functionality where one can add some code or changes in the existed API created by Rest-Hapi.

Thanks

**Comment by JKHeadley** [comment]
Thanks for your clarification.  Hopefully I can work on #27 soon.  As for custom functions you always have the option of adding "static" functions to the `Schema.statics` property.  Consider the below example code borrowed from the [appy](https://github.com/JKHeadley/appy/blob/master/server/models/session.model.js) project:

```javascript
'use strict';

const Bcrypt = require('bcryptjs');
const Uuid = require('node-uuid');

module.exports = function (mongoose) {
  const modelName = "session";
  const Types = mongoose.Schema.Types;
  const Schema = new mongoose.Schema({
    user: {
      type: Types.ObjectId,
      ref: "user"
    },
    key: {
      type: Types.String,
      required: true
    },
    passwordHash: {
      type: Types.String,
      required: true
    }
  }, { collection: modelName });

  Schema.statics = {
    collectionName: modelName,
    enableSoftDelete: false,
    routeOptions: {
      associations: {
        user: {
          type: "ONE_ONE",
          model: "user"
        }
      }
    },
    findByCredentials: function (_id, key, Log) {

      let session = {};

      return mongoose.model('session').findById(_id)
        .then(function (result) {
          session = result;
          if (!session) {
            return false;
          }

          return session.key === key ? session : false;
        });
    }
  };

  return Schema;
};

```

Then wherever you need to access/call this function you can use code similar to the following:

```javascript
const Session = mongoose.model('session');
Session.findByCredentials(_id, key, Log)
   .then(function(result) {
      /** do work **/
   });
```

**Comment by parveen-oodles** [comment]
@JKHeadley  Thanks a lot. :+1:

**Comment by parveen-oodles** [comment]
But what if i need request object in my function. And the API is implicitly created by Rest-Hapi. I can do one thing for this i can call my function from validateFunc of Auth and pass request object from there but what if there is no authentication there for that API than how can i get the request object  in my function.
would appreciate if please clear me on this .
Thanks

**Comment by JKHeadley** [comment]
That would depend on when and where you intend to use your function.  For example, say I had a static function for the ``Session`` model that had the request as a parameter:

```javascript
modifyRequestFunc: function (request) {
/***code to modify request***/
}
```

I could then call this function during any part of the Hapi request lifecycle where the request object is available.  As you already stated, the ``validateFunc`` function is one place where ``request`` is available. A custom endpoint would be another option.  Hopefully in a near-future version of rest-hapi the request will be available in middleware functions (as we discussed in #19).

Other options would be to set up an extension to the [request lifecycle](https://hapijs.com/api#request-lifecycle).  This can be done wherever the ``server`` object is available (such as after the rest-hapi plugin is registered).  The code below demonstrates this with the ``onPreHandler`` extension:

```javascript
server.ext('onPreHandler', function (request, reply) {
        const Mongoose = require('mongoose');
        const Session = Mongoose.model('session');

        Session.modifyRequestFunc(request);
    
        return reply.continue();
});
```

This code would then run before every handler on every request.

**Comment by JKHeadley** [comment]
@parveen-oodles the request object is now available in middleware functions.  Please see the [changelog](https://github.com/JKHeadley/rest-hapi/blob/master/CHANGELOG.md#0200---2017-08-29-breaking) for details.
