### ISSUE TITLE
Boom.serverTimeout is not a function

### ISSUE THREAD

**Issue by tamias** [JKHeadley/rest-hapi#45]
error-helper.js calls `Boom.serverTimeout`, but Boom doesn't define that method.  Which HTTP error is intended for these cases?  Perhaps `Boom.badImplementation`, which corresponds to HTTP 500 Internal Server Error?

**Comment by JKHeadley** [comment]
Looks like it was removed in recent versions.  I agree that `Boom.badImplementation` is a fitting replacement.

**Comment by tamias** [comment]
Digging into this a little more, I discovered that `Boom.serverTimeout` (503 Service Unavailable) was renamed to `Boom.serverUnavailable` in v3.2.2, and the `Boom.serverTimeout` alias was removed in v4.0.0.

With that in mind, which error would you prefer, badImplementation or serverUnavailable?

**Comment by JKHeadley** [comment]
I still feel badImplementation is more fitting.

**Comment by tamias** [comment]
That will save me some time then. 😄
