### ISSUE TITLE
Defining Schema

### ISSUE THREAD

**Issue by samseralam** [JKHeadley/rest-hapi#49]
If there is a field in schema like this:

name: {
            firstName: {
                type: Types.String,
                required: true
            },
            lastName: {
                type: Types.String,
                required: true
            }
}

when i am going to save, it says : "message": "\"value\" at position 0 fails because [\"name\" is not allowed]
So how can save it on above schema?

**Comment by JKHeadley** [comment]
Try:

```
        name: {
            firstName: {
                type: Types.String,
                required: true
            },
            lastName: {
                type: Types.String,
                required: true
            },
            type: Types.Object
        }
```
