### ISSUE TITLE
support "soft" delete of mongo documents

### ISSUE THREAD

**Issue by JKHeadley** [JKHeadley/rest-hapi#6]
Documents are marked as "deleted" but remain in the db.

**Comment by Metatricity** [comment]
I'm assuming on exit (or some sort of switch) these will be deleted?

**Comment by JKHeadley** [comment]
The idea behind this is for consistency/recordkeeping, so by default they would not be deleted.  However I would like to provide a "clean" function that would delete all "soft" deleted docs on command.  Also possibly support some sort of TTL that would flag docs to be deleted after a certain specified duration.

**Comment by Metatricity** [comment]
I think I understand now. Best of luck on your project from here forth!

**Comment by JKHeadley** [comment]
Thanks!

**Comment by JKHeadley** [comment]
Added basic soft-delete functionality.
