### ISSUE TITLE
question: dynamic fields in model

### ISSUE THREAD

**Issue by jobberwalker** [JKHeadley/rest-hapi#68]
Hi,
I'd like to put some dynamic attributes to the model and I was thinking to use:

`attributes : [new mongoose.Schema({
        Name: {type: String},
        Value : {type: String}
    }, {strict: false})
    ]`

or even 

`attributes : [mongoose.Schema.Types.Mixed]`

Is this something which is not recommended?

Thanks
JB

**Comment by JKHeadley** [comment]
@jobberwalker I haven't tried those specific formats before, but they should work.  The only thing it might throw off would be validation.
