### ISSUE TITLE
Handling duplicate entry error gracefully.

### ISSUE THREAD

**Issue by rahil471** [JKHeadley/rest-hapi#73]
Hi, currently if there is an attempt of duplicate entry on unique keys, the system sends a 500 status with an Internal server error. 
I'm thinking that we should handle this as a special case, coz in most cases the users of application would like to know that duplicate data is being inserted.

I suggest we should send a 409 Conflict with a duplicate content message.
Would like to hear your thoughts on this.

**Comment by JKHeadley** [comment]
@rahil471 I agree.  I added this feature to v0.34.0
