### ISSUE TITLE
Where to find documentation for older version

### ISSUE THREAD

**Issue by parveen-oodles** [JKHeadley/rest-hapi#75]
Hi JKHeadly,

I am just wondering to know where can i find the documentation for previous version of Rest-Hapi, like for example you changed param in Post and Pre of Create middle-ware , but what if somebody used older version as you updated the documentation so where i can find the older documentation for Middle-ware like i want to check the param which were send in say 0.23.2 version. 
In the changelog.md you define what you changed but documentation wasn't there. So please help me in this concern because as i updated my rest-hapi version most of the things are not working properly.
Thanks

**Comment by JKHeadley** [comment]
@parveen-oodles As you mentioned, you can view most of the changes in the changelog. 
 Any breaking changes are noted there and changes to function calls/parameters should be [documented](https://github.com/JKHeadley/rest-hapi/blob/master/CHANGELOG.md#0200---2017-08-29-breaking)

Another option would be to view the history of the [Readme file](https://github.com/JKHeadley/rest-hapi/commit/9fc221cae13339bb0430e6be3d91579df110d9bb?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8).
