### ISSUE TITLE
Populate associations of embedded docs

### ISSUE THREAD

**Issue by drphelps** [JKHeadley/rest-hapi#81]
I'm not sure if this is a feature request or something that I'm not doing correctly. I would like to be able to populate associations of (deeply) nested embedded documents. For example, if I have a structure like the following where `child` is an embedded document and `grandChildren` are in their own collection, I'd like to be able to call an endpoint to populate the referenced `grandChildren` docs.
```
parent: {
  child: {
    grandChildren: [1, 2, 3];
  }
}
```
 Right now I'm handling it with middleware and a faux association so I can hit an endpoint like `/parent/1?$embed=grandChildren` but this feels like a workaround. Is there a more straightforward way to accomplish this? It seems like it should be possible with Model.populate.

**Comment by JKHeadley** [comment]
Yes this should be possible.  Would you be able to post your model code here? 

As a quick answer, if your models and associations are defined correctly you should be able to accomplish this with something like `GET /parent/1?$embed=child.grandchildren`

Please reference the docs on [populating nested associations](https://github.com/JKHeadley/rest-hapi#populate-nested-associations) for more info.

**Comment by drphelps** [comment]
@JKHeadley, I realize I may have oversimplified my setup. Here are pared down versions of my schemas.
```
const pageSchema = new Schema({
  layout: {
    type: Types.String,
    ref: 'layout',
    required: true,
  },
});

const contentSchema = new Schema(
  {
    pages: {
      type: [pageSchema],
    },
  },
  {
    _id: false,
  }
);

const appSchema = new mongoose.Schema({
  draft: {
    type: contentSchema,
  },
});
```
As you can see, `draft` is an embedded document and not an association itself. Hitting `GET /app/1?$embed=draft.pages.layout` throws "Association not found".

**Comment by JKHeadley** [comment]
@drphelps Thanks for code, however this format does not seem to be following the requirements for rest-hapi associations, therefore the `$embed` parameter will not function correctly.  Please [reference the docs](https://github.com/JKHeadley/rest-hapi#associations) on how to set up associations between models.

**Comment by drphelps** [comment]
Ok, thanks for your attention. I figured that would be the answer.
