### ISSUE TITLE
Logging Transporters 

### ISSUE THREAD

**Issue by rahil471** [JKHeadley/rest-hapi#82]
Hey there again. 

Is there a way to configure the rest-hapi logger to use an alternate transport like file or database? 

If not then could this be overwritten/ monkey patched outside the rest-hapi framework?

**Comment by JKHeadley** [comment]
@rahil471 Hmm, that's an interesting question. For reference, the logging library being used is [loggin](https://www.npmjs.com/package/loggin). However I don't believe you can configure the internal logger for generated endpoints currently (besides the loglevel).

I would think your best bet would be to grab stdout and redirect it to your desired location.  For some of my projects I use the [forever](https://www.npmjs.com/package/forever) library to run the server and it redirects all the server output to a log file.

**Comment by rahil471** [comment]
Hmm correct, in that case, I'm using pm2. So I can grab the logs from there.  Thanks.
