### ISSUE TITLE
Policies do not run

### ISSUE THREAD

**Issue by jobberwalker** [JKHeadley/rest-hapi#83]
Hello,
I am wondering what I did wrong here because it doesn't enter the policy script. I took the appy demo with rest-hapi@0.37.1. Then added in config.js
`const config = {
  enablePolicies: true,
.....`

in user.model.js added : 

` Schema.statics = {
    collectionName: modelName,
    routeOptions: {
      policies: {
        rootPolicies: ['addClient']
      },`

then in the root of the project added ./policies/addClient.js : 

`'use strict';
const Boom = require('boom');
let addClient = function(request, reply, next) {
    let Log = request.logger;
    try {
        console.log("addClient");
    }
    catch (err) {
        Log.error("ERROR", err);
        return next(Boom.badImplementation(err), false);
    }
};

addClient.applyPoint = 'onPreHandler';
module.exports = addClient;
`

**Comment by JKHeadley** [comment]
@jobberwalker make sure when you edit the appy config that you add the `enablePolicies` property to the `restHapiConfig` property of the root `config` object:

https://github.com/JKHeadley/appy/blob/576fa097209896cb1355367497769b1f05d92e91/config.js#L105

**Comment by jobberwalker** [comment]
Thank you JKHeadley. I did it wrong adding in `config` section instead of `restHapiConfig`. Everything is working fine. ;-)
