### ISSUE TITLE
Support Mongoose's runValidators option

### ISSUE THREAD

**Issue by tamias** [JKHeadley/rest-hapi#85]
I would like a way to specify Mongoose's `runValidators` option in rest-hapi's calls to `update()`, `findOneAndUpdate()`, and `findByIdAndUpdate()`:

http://mongoosejs.com/docs/validation.html#update-validators

In particular, I want Mongoose validation to occur when updating a document with rest-hapi's update handler.

**Comment by tamias** [comment]
As an example, here's a commit that hard-codes it in the update handler: https://github.com/pangeamedia/rest-hapi/commit/febaaabe4025139ab4f5ff6452bf321d69f79f94

To do a proper implementation, I'd want to have a name for the config setting, and to know which update calls should use it.

The config setting could be something like `enableMongooseUpdateValidation` or `enableMongooseRunValidators`.  (Or the setting could be `mongooseUpdateOptions` and specify a full options object, but that seems like overkill to me.)

These are all the mongoose update calls I found in the code base:

- utilities/handler-helper.js:
  - _updateHandler: model.findByIdAndUpdate()
  - _deleteOneHandler: model.findByIdAndUpdate()
  - _setAssociation: linkingModel.findOneAndUpdate(), ownerModel.findByIdAndUpdate() x2, childModel.findByIdAndUpdate(
  - _removeAssociation: ownerModel.findByIdAndUpdate() x2, childModel.findByIdAndUpdate()
- gulp/update-associations.js:
  - addEmbeddedAssociation: model.findByIdAndUpdate() x2
  - removeEmbeddedAssociation: dummyModel.findByIdAndUpdate()
- seed/user.model.js:
  - Password Update Endpoint: model.findByIdAndUpdate()

Are there any of those calls that shouldn't get the runValidators option, if it's enabled in the config?

**Comment by JKHeadley** [comment]
Hi @tamias 

Sorry for the delayed response.  I like this idea. I don't have a lot of time to look into this right now, but I would expect for this feature only the calls within `utilities/handler-helper.js` should need to be affected by the new config setting.

**Comment by tamias** [comment]
Here's a PR: https://github.com/JKHeadley/rest-hapi/pull/89
