### ISSUE TITLE
How can one reuse the function(simple javascript function) defined on one model into other

### ISSUE THREAD

**Issue by parveen-oodles** [JKHeadley/rest-hapi#86]
Hi JKHeadly,

I just want to reuse one of my function written in one model.js file and i want to reuse the same in my other model.js , So how can i achieve the same. Like in nodejs we simply write at the end of file i.e:-
Suppose i  have a model user and there is one function test in user model . i want to call the same function test from my another file i.e employee. So i simply export in the user model like this:-

module.exports ={
test:test
} 

**And require that js file in the required file and call the function like:-**

var demo = require('./user.js')
demo.test()
How can i achieve the same for simple javascript function as well as some other function that are written in the extra-endpoint.

Please help me for the same.
Thanks

**Comment by JKHeadley** [comment]
Hi @parveen-oodles,

This can be done using mongoose static functions. For example, using the following model:
```javascript
'use strict';

module.exports = function (mongoose) {
  var modelName = "role";
  var Types = mongoose.Schema.Types;
  var Schema = new mongoose.Schema({
    name: {
      type: Types.String,
      required: true,
      unique: true
    },
    description: {
      type: Types.String
    }
  }, { collection: modelName });
    
  Schema.statics = {
    collectionName:modelName,
    routeOptions: {
    },
    test: function () {
      console.log("TEST");
    },
  };

  return Schema;
};
```

You can call the `test` function somewhere else like so:

```javascript
var mongoose = require('mongoose');
mongoose.model('role').test();
```
