### ISSUE TITLE
http://localhost:8124/ does not work

### ISSUE THREAD

**Issue by jadgsam** [JKHeadley/rest-hapi#92]
Hi,
I know this is a very basic question but I am following instructions and after making the first node api.js I cannot access the swagger docs. 

jadsam@Joses-MacBook-Pro:~/Documents/VM/VMD$ node api.js 
[02:05:17.473] 25990 LOG      api/mongoose — Connecting to Database...:
[02:05:17.479] 25990 LOG      api/mongoose — 	URI: `mongodb://localhost/rest_hapi`
[02:05:17.490] 25990 LOG      api — Initializing Server...
[02:05:17.731] 25990 NOTE     api/user/Password Update — Generating Password Update endpoint for user

Maybe I am doing something wrong, please let me know your comments .

Thanks in advance,
Jose

**Comment by JKHeadley** [comment]
hi @jadgsam would you mind posting your `api.js` code here? That could give more context into what might be going wrong.

**Comment by anhbinhvodanh** [comment]
@JKHeadley I got same error when use api.js in your document.

**Comment by JKHeadley** [comment]
@jadgsam  @anhbinhvodanh apologies, looks like the docs were a bit out of date. Please try the updated code below with the port defined directly:

```javascript
'use strict';

let Hapi = require('hapi');
let mongoose = require('mongoose');
let restHapi = require('rest-hapi');

function api(){

  let server = new Hapi.Server();

  console.log("SERVER:", restHapi.config.server)

  server.connection({ port: 8124 });

  server.register({
      register: restHapi,
      options: {
        mongoose: mongoose
      }
    },
    function() {
      server.start();
    });

  return server;
}

module.exports = api();
```

**Comment by jadgsam** [comment]
Thanks for your answer, now it works
