### ISSUE TITLE
Model definition and optional fields

### ISSUE THREAD

**Issue by jadgsam** [JKHeadley/rest-hapi#93]
Hi @JKHeadley,
I was wondering if the model definition supports adding optional fields (no matter what type they are) in order to allow the consumer of the service not sending some of the fields.

Please let me know if there is any way to setup this in the model definition.

Thanks for your support

**Comment by JKHeadley** [comment]
Hi @jadgsam,
If I understand you correctly, I think you can use [route validation](https://github.com/JKHeadley/rest-hapi#route-validation) to accomplish this. For example, setting `allowOnRead` to `false` will prevent a user from receiving a certain field on any `GET` request.

**Comment by jadgsam** [comment]
Hi @JKHeadley,
Excellent thanks for your feedback, the section route validation was exactly what I was looking for.
