### ISSUE TITLE
Refactor using 'async/await'

### ISSUE THREAD

**Issue by JKHeadley** [JKHeadley/rest-hapi#97]
Should help convert to Hapi 17

**Comment by tkvw** [comment]
Hello Jusin, 

I stumbled on this library when testing Hapi and I think it looks really nice! Can you give an update about the progress to update to Hapi 17? I see there's a `refactor/async_await` branch where you've done some recent work. Is there still a lot of work left? Can I be of some assistance?

**Comment by JKHeadley** [comment]
Hi @tkvw, thanks! I'm working on a major version update that includes Hapi 17 support, the `develop` branch has most of the recent updates. I hope to finish the `async/await` updates soon. If you'd like to contribute you can take a look at the [remaining tasks](https://github.com/JKHeadley/rest-hapi/milestone/9) and see if anything interests you. I'm always open to help (or suggestions)! 😉

**Comment by tkvw** [comment]
Thanks for the (quick!) update, what `develop` branch do you mean? I see recent activity on the `master`, `refactor/async_await` and `refactor/eslint_prettier` branches. The `development` branch is far behind `master`. Before helping I'll try out the library some more and hope I can give some suggestions/pr's.

**Comment by JKHeadley** [comment]
Apologies, it looks like I forgot to push the `develop` branch to origin. It should be available now. That sounds like a good plan. I'll look forward to hearing back from you.

**Comment by JKHeadley** [comment]
Finished with cefa439eb6823000818381a25cec3f4fa03b15af
